### ISSUE TITLE
Segurança: Vários tokens sensíveis expostos no código

### ISSUE THREAD

**Issue by gsilvapt** [tomahock/basecovid19#4]
hey! congrats pelo projeto.

Entendo que se trata de um projeto open source e, embora não tenha espreitado toda a fonte, provavelmente estás a usar a BD Mongo para guardar os contratos mas expões as passwords todas no código e no compose.

Há várias formas de injectar isso. Podemos marcar uma sessão e ajudo-te, se precisares. Mesmo sendo um projeto open source, não devemos permitir que sejam um free pass para a malta maliciosa fazer asneiras.... :)

**Comment by cenourinha** [comment]
A key do h-captcha e os dados da proxy da PIA (privateinternetaccess) também.

**Comment by tomahock** [comment]
Removi e fiz revoke da proxy.

Do hcaptcha tou a tentar perceber como se faz revoke :) 

A proxy não era suposto ter ido para o repo. mas já lá está.. Meti flag para ligar ou desligar!
O hCaptcha.. bem.. colei o token para testar, comentei para ir buscar ao ENV.. e esqueci de remover 🤦‍♂️🤦‍♂️

**Comment by tomahock** [comment]
Segundo o suporte do hCaptcha esta key não dá acesso a nada nas contas gratuitas (é o caso). Apenas serve para validar a resposta.

Passei de qualquer maneira para o ENV.
