### ISSUE TITLE
Bug: O link das entidades adjudicantes nos detalhes de contratos não funciona

### ISSUE THREAD

**Issue by miguelrocha19** [tomahock/basecovid19#5]
Exemplo: https://base-covid19.pt/contrato?id=6496982 

 Se clicarmos em cima no link para 'Município da Trofa' este funciona. Contudo se fizermos o mesmo em baixo, na entidade adjudicante, este não funciona.

**Comment by tomahock** [comment]
A base de dados das entidades ainda está a ser populada. Ainda faltam bastantes!
Mais dia menos dias vão aparecer.

**Comment by miguelrocha19** [comment]
Não me parece ser esse o caso. Isto porque se clicares em cima naquele exemplo a entidade aparece:

https://base-covid19.pt/entidade?nif=504296434

O erro não é de entidade não encontrada. É o próprio botão de link que não me parece ter ação.

**Comment by tomahock** [comment]
Percebido e corrigido!
Obrigado :)
